<?php

namespace App\Payloads\Windows;

use App\Exception;
use App\Models\Payload;

/*enum PayloadType: string
{
  case RESTRICTIONS = 'RESTRICTIONS';
}

enum ApplePayloadType: string
{
  case RESTRICTIONS = 'RESTRICTIONS';
}

enum DeviceModel: string
{
  case IPAD = 'ipad';
  case IPHONE = 'iphone';
  case IPOD = 'ipod';
  case APPLETV = 'appletv';
}*/

class Windows_Configuration extends Payload
{

  public array $availableOs = ['Windows'];

  public function getIcon(): string
  {
    return "https://nextcloud.chimpa.eu/testmdm/panel/latest/assets/img/payloads/WINDOWS_CONFIG.png";
  }

  public function getConfig(): array
  {
    return [
      "show" => true,
      "title" => "Configurazioni Windows",
      "description" => "Utilizza questa sezione per configurare le impostazioni di sicurezza",
      "img" => "https://nextcloud.chimpa.eu/testmdm/panel/latest/assets/img/payloads/PIN_COMPLEXITY.png"
    ];
  }

  public function getSchema(string $osType): array
  {
    $schema = [
      [
        "id" => 1,
        "os" => ["Windows"],
        "label" => "Le policy MDM prevalgono sui criteri di gruppo",
        "field_id" => "Field id: (mdmWinsOverGP)",
        "value" => true,
        "input_type" => "checkbox",
        "description" =>
        "Se abilitato, in caso di conflitti, il criterio MDM viene applicato, il criterio di gruppo è bloccato",
        "options" => [],
      ],
      [
        "id" => 2,
        "os" => ["Windows"],
        "label" => "Richiedi store privato",
        "field_id" => "Field id: (requirePrivateStoreOnly)",
        "value" => false,
        "input_type" => "checkbox",
        "description" =>
        "Se abilitato l\'utente potrà utilizzare solo uno store privato",
        "options" => [],
      ],
      [
        "id" => 3,
        "os" => ["Windows"],
        "label" => "Disabilita pulsante Disconnetti dal MDM",
        "field_id" => "Field id: (disableUnenrollButton)",
        "value" => true,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 4,
        "os" => ["Windows"],
        "label" => "Orario intervallo attivo (ora inizio)",
        "field_id" => "Field id: (updateActiveHoursStart)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
        ],
      ],
      [
        "id" => 5,
        "os" => ["Windows"],
        "label" => "Orario intervallo attivo (ora fine)",
        "field_id" => "Field id: (updateActiveHoursEnd)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
        ],
      ],
      [
        "id" => 6,
        "os" => ["Windows"],
        "label" => "Intervallo massimo attività",
        "field_id" => "Field id: (updateActiveHoursMaxRange)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => ["---", 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
      ],
      [
        "id" => 7,
        "os" => ["Windows"],
        "label" => "Comportamento dell\'aggiornamento automatico",
        "field_id" => "Field id: (updateAllowAutoUpdate)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Notificare all\'utente prima di scaricare l\'aggiornamento",
          "Installare automaticamente l\'aggiornamento e quindi notificare all\'utente di pianificare un riavvio del dispositivo",
          "Installazione automatica e riavvio",
          "Installazione automatica e riavvio in un momento specificato (utente può interrompere)",
          "Installazione automatica e riavvio in un momento specificato (utente non può interrompere)",
          "Disattivare gli aggiornamenti automatici",
          "Gli aggiornamenti scaricano e installano automaticamente in un momento ottimale determinato dal dispositivo",
        ],
      ],
      [
        "id" => 8,
        "os" => ["Windows"],
        "label" =>"Scadenza in giorni prima dell\'esecuzione automatica di un riavvio pianificato al di fuori degli orari di attività ",
        "field_id" =>
        "Field id: (updateAutoRestartDeadlinePeriodInDaysForFeatureUpdates)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
        ],
      ],
      [
        "id" => 9,
        "os" => ["Windows"],
        "label" =>"Numero di giorni prima dell\'installazione automatica degli aggiornamenti delle funzionalità",
        "field_id" => "Field id: (updateConfigureDeadlineForFeatureUpdates)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
        ],
      ],
      [
        "id" => 10,
        "os" => ["Windows"],
        "label" =>"Numero di giorni prima dell\'installazione automatica degli aggiornamenti qualitativi",
        "field_id" => "Field id: (updateConfigureDeadlineForQualityUpdates)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
        ],
      ],
      [
        "id" => 11,
        "os" => ["Windows"],
        "label" =>"Ritardare il riavvio automatico fino alla scadenza del periodo di tolleranza",
        "field_id" => "Field id: (updateConfigureDeadlineNoAutoReboot)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 12,
        "os" => ["Windows"],
        "label" =>"Rinvia gli aggiornamenti delle funzionalità per il numero di giorni specificato",
        "field_id" => "Field id: (updateDeferFeatureUpdatesPeriodInDays)",
        "value" => "",
        "input_type" => "text",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 13,
        "os" => ["Windows"],
        "label" => "Rinvia gli aggiornamenti qualitativi per il numero di giorni specificato",
        "field_id" => "Field id: (updateDeferQualityUpdatesPeriodInDays)",
        "value" => "",
        "input_type" => "text",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 14,
        "os" => ["Windows"],
        "label" => "Ritarda gli aggiornamenti fino a un massimo di",
        "field_id" => "Field id: (updateActiveHoursMaxRange)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Non ritardare",
          "1 settimana",
          "2 settimane",
          "3 settimane",
          "4 settimane",
        ],
      ],
      [
        "id" => 15,
        "os" => ["Windows"],
        "label" => "Ritarda altri aggiornamenti fino a un massimo di",
        "field_id" => "Field id: (updateDeferUpgradePeriod)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Non ritardare",
          "1 mese",
          "2 mesi",
          "3 mesi",
          "4 mesi",
          "5 mesi",
          "6 mesi",
          "7 mesi",
          "8 mesi",
        ],
      ],
      [
        "id" => 16,
        "os" => ["Windows"],
        "label" => "Sospendere gli aggiornamenti delle funzionalità per un massimo di 35 giorni.",
        "field_id" => "Field id: (updatePauseFeatureUpdates)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 17,
        "os" => ["Windows"],
        "label" => "Sospendere gli aggiornamenti qualitativi per un massimo di 35 giorni.",
        "field_id" => "Field id: (updatePauseQualityUpdates)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 18,
        "os" => ["Windows"],
        "label" => "Pianifica giorno di installazione degli aggiornamenti",
        "field_id" => "Field id: (updateScheduledInstallDay)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Lunedì",
          "Martedì",
          "Mercoledì",
          "Giovedì",
          "Venerdì",
          "Sabato",
          "Domenica",
        ],
      ],
      [
        "id" => 19,
        "os" => ["Windows"],
        "label" => "Pianificare l\'installazione dell\'aggiornamento nella prima settimana del mese",
        "field_id" => "Field id: (updateScheduledInstallFirstWeek)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 20,
        "os" => ["Windows"],
        "label" => "Pianificare l\'installazione dell\'aggiornamento nella seconda settimana del mese ",
        "field_id" => "Field id: (updateScheduledInstallSecondWeek)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 21,
        "os" => ["Windows"],
        "label" => "Pianificare l\'installazione dell\'aggiornamento nella terza settimana del mese",
        "field_id" => "Field id: (updateScheduledInstallThirdWeek)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 22,
        "os" => ["Windows"],
        "label" => "Abilitare la sicurezza basata sulla virtualizzazione",
        "field_id" => "Field id: (enableVirtualizationBasedSecurity)",
        "value" => false,
        "input_type" => "checkbox",
        "description" => "",
        "options" => [],
      ],
      [
        "id" => 23,
        "os" => ["Windows"],
        "label" => "Configurazione dell\'avvio sicuro",
        "field_id" => "Field id: (updateSystemGuardLaunch)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Configurabile dall\'utente",
          "Abilitare l\'avvio sicuro se supportato dall\'hardware",
          "Disabilitare l\'avvio sicuro",
        ],
      ],
      [
        "id" => 24,
        "os" => ["Windows"],
        "label" => "Configurazione credential guard",
        "field_id" => "Field id: (updateLsaCfgFlags)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Disabilitare Credential Guard in remoto se configurato in precedenza senza UEFI Lock",
        ],
      ],
      [
        "id" => 25,
        "os" => ["Windows"],
        "label" => "Confiugurazione del livello di sicurezza",
        "field_id" => "Field id: (updateRequirePlatformSecurityFeatures)",
        "value" => "---",
        "input_type" => "multiselect",
        "description" => "",
        "options" => [
          "---",
          "Attivare VBS con Secure Boot",
          "Attivare VBS con Secure Boot e accesso diretto alla memoria",
        ],
      ],
    ];

    if (in_array($osType, $this->availableOs)) {
      return $schema;
    }else{
      return [];
      // throw \Exception::class
    }
  }
}
